apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: scj4p8i09-go 
  janus-idp.io/tekton: scj4p8i09-go
  backstage.io/kubernetes-id: scj4p8i09-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: scj4p8i09-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  