apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: scj4p8i09-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: scj4p8i09-go 
  name: scj4p8i09-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: scj4p8i09-go 
